experiment:
    type: 'cv'  # 'single', 'cv'
    n_folds: 10  # number of folds to use if cv is active
    np_random_seed: 52
    years: [1]
    shuffle_data: True
    test_share: 0.1
    algorithm: 'random_guess'
algo_params:
    param: 1
analysis:
    print_results: ['classification_report', 'log_loss', 'accuracy', 'roc_auc']
    plot_roc: True
