experiment:
    type: 'cv'  # 'single', 'cv'
    n_folds: 10  # number of folds to use if cv is active
    np_random_seed: 52
    years: [1]
    shuffle_data: True
    test_share: 0.1
    algorithm: 'rf'
imputer_params:
    strategy: 'mean'  # 'mean', 'min'
    new_features: 'sum'  # False, 'sum', '1-hot'
processor_params:
    normalize: True
algo_params:
    n_estimators: 10
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    n_jobs: 1
    verbose: 0
    warm_start: False
    criterion: 'entropy'
    bootstrap: False
    oob_score: False
    max_features: 'auto'
    #max_depth: int(None)
    #max_leaf_nodes: None
    #min_impurity_split: None
    #class_weight: None
analysis:
    print_results: ['classification_report', 'log_loss', 'accuracy', 'roc_auc']
    plot_roc: True
